### ISSUE TITLE
Fixes for Lymphgen in get_gambl_metadata and collate_lymphgen

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#120]
The way we track lymphgen results has changed such that one result is pre-populated into gambl_biopsy_metadata.tsv in the gambl repository and all the different flavours of outputs are individually in version control in that repo under versioned_results/LymphGen

Currently, collate_lymphgen is using the wrong path to load these data and this is clobbering some of the data in our metadata table. The call to collate_lymphgen in get_gambl_metadata is actually now obsolete and that line should be removed. The function is still useful for other applications (e.g. when called by collate_results). However, it needs to be updated to use the files in the correct path, mentioned above. Please update that function to use the correct path. This should go hand-in-hand with the addition of a new global config value e.g. versioned_results in the GAMBLR config. The error message that is only triggered in verbose mode should also be changed to be triggered by default if these files are not found. The fact that this error was silent has made it harder to track down.

**Comment by lkhilton** [comment]
I think this is resolved?

**Comment by rdmorin** [comment]
This was not fully resolved as far as I can tell. Collate_results doesn't call this function. Was there a commit or PR for what was changed when this was marked as resolved?
